### ISSUE TITLE
Add projects that make those who follow the map strong in the back-end

### ISSUE THREAD

**Issue by GAbdulWahab** [Eyadhamza/Backend-Roadmap-2022#1]

**Comment by Eyadhamza** [comment]
Please, Clarify your issue.

**Comment by GAbdulWahab** [comment]
@Eyadhamza  okay, I mean  can you add a section called projects that anyone follows your road map make it to enhance their knowledge  or to be strong in the back end  
and also why you didn't add python as the backend language?
